import { v1 } from 'uuid';
import { ExperienceItemType } from '../types';

export const experience: ExperienceItemType[] = [
  {
    id: v1(),
    company: 'NybleCraft',
    url: 'https://nyblecraft.com/',
    position: 'Front-end Developer',
    responsibility: [
      'Code developmen',
      'Refactor legacy code',
      'Project evaluation',
      'Team supporting',
      'Meetings with clients',
      'Testing',
      'SEO optimization',
    ],
    stack: [
      'React',
      'Gatsby',
      'JavaScript',
      'TypeScript',
      'Docker',
      'Node.js',
      'Express',
      'Nginx',
      'MobX',
      'WebSocket',
      'OOP',
      'Rest API',
      'Swagger',
      'Figma',
      'Material-UI',
      'SCSS',
      'Styled-components',
      'Emotion',
      'Git',
      'GitHub',
      'Yarn',
      'ESLint',
      'Husky',
      'Prettier',
      'Day.js',
    ],
    timeStart: 'April 2022',
    timeEnd: 'present time (current job)',
  },
  {
    id: v1(),
    company: 'LLC "Ivashin"',
    url: 'https://park.by/residents/ivashin/',
    position: 'Front-end Developer',
    responsibility: [
      'Setting and monitoring tasks',
      'Code developmen',
      'Refactor legacy code',
      'Project evaluation',
      'Code refactoring',
      'Team supporting',
      'Meetings with clients',
      'Testing',
    ],
    stack: [
      'React-native',
      'Expo',
      'JavaScript',
      'TypeScript',
      'EAS',
      'Firebase',
      'Redux Toolkit',
      'Rest API',
      'Axios',
      'Swagger',
      'Figma',
      'StyleSheets',
      'Git',
      'GitHub',
      'Postman',
      'Android studio',
      'Google-map',
      'Npm',
      'ESLint',
      'Prettier',
      'Moment.js',
    ],
    timeStart: 'September 2021',
    timeEnd: 'April 2022',
  },
];
